name: Tickets
main: com.lebelw.Tickets.Tickets
version: 0.5 (#${env.BUILD_NUMBER})
commands:
    ticket:
        description: Take care of the tickets
        usage: /ticket
    business:
        description: Take care of the business support
        usage: /business